# Generated by Django 2.2.13 on 2022-03-15 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('image', models.ImageField(help_text='Recommended Size 70X70px', upload_to='form')),
                ('Costumer_name', models.CharField(max_length=200)),
                ('titl', models.CharField(max_length=200)),
            ],
        ),
    ]
